[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-openapi/analysis"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/errors"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/loads"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/swag"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/validate"
  version = "0.16.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
